### ISSUE TITLE
left outer join from tpc-h-13 has bug

### ISSUE THREAD

**Issue by fzhedu** [dase/CLAIMS#141]
SELECT
        C_COUNT,
        COUNT(*) AS CUSTDIST
FROM
        (
                SELECT
                        C_CUSTKEY,
                        COUNT(O_ORDERKEY) AS C_COUNT
                FROM
                        CUSTOMER LEFT OUTER JOIN ORDERS ON
                                C_CUSTKEY = O_CUSTKEY
                                AND O_COMMENT NOT LIKE '%UNUSUAL%DEPOSITS%'
                GROUP BY
                        C_CUSTKEY
        ) AS C_ORDERS
GROUP BY
        C_COUNT
ORDER BY
        CUSTDIST DESC,
        C_COUNT DESC;

result compared with hawq isn't right!+---------+----------+
| C_COUNT | CUSTDIST |
+---------+----------+
|    1    |  50021   |
|   10    |   6577   |

but in hawq 
 c_count | custdist 
---------+----------
       0 |    50004
      10 |     6577
。
。
       1 |       17
please not c_count=0,1

**Comment by FishYoung** [comment]
This is caused by wrong SQL statement. It should be '%unusual%deposits%' instead of upper case.
