### ISSUE TITLE
Limit cause support

### ISSUE THREAD

**Issue by wangli1426** [dase/CLAIMS#29]
Is' about the time to support limit cause in Claims.

In particular, we plan to support the following three queries:

1.This query returns the first 5 tuples of T
```sql
select * from T limit 5;
```
2.This query returns 10 tuples starting from the 5-th tuple, e.g., the 5-th tuple and the following 9 tuples.
```sql
select * from T limit 5,10;
```
3.This query returns the 5-th tuple and all the following tuples.
```sql
select * from T limit 5,-1;
```

@fzh: Please check in mysql whether the semantics of the above three queries are the same as I describe.

@fzh: I will first extend the physical limit iterator to support the mentioned functions, and then implement the logical operator, which will be called by sql parser. After that, please extend sql parser to support limit cause.

**Comment by fzhedu** [comment]
we have constructed one LogicalLimit, insulated limit function from LogicalPlanRoot.
