### ISSUE TITLE
Attribute name is a mass

### ISSUE THREAD

**Issue by wangli1426** [dase/CLAIMS#43]
@egraldlo @fzhedu 
After the table name is added to attribute name in the latest version, getting attribute by name becomes a kind of mass.
The attribute name in the form of "T.A" should be separately stored as "T" and "A". And we should provide a multi-functioning interface, say, getAttribute(const char* attribute_name, const char* table_name=0, const char* database_name=0), in which table_name and database_name can be omitted.

**Comment by fzhedu** [comment]
now just getAttribute(column_name) is used, actually, column_name= table.column
